### ISSUE TITLE
Inconsistency on restart: I am able to create instance, and see them in monitor, while workflows screen is empty

### ISSUE THREAD

**Issue by anborg** [zeebe-io/zeebe-simple-monitor#88] opened 2019-11-03 15:32 UTC
**Describe the bug**
Before shutdown of broker I had 1 work-flow and few instance. 

When I restart of broker & monitor.= here is what I expect/observe.

**Expected**: I expect these WF & IN to disappear on shutdown/restart. Or both WF and IN reappear if persisted.
**Actual** : No workflow displayed in monitor, but I can keep creating instances, and instances are completed.

It is possible Hazelecast in server is exporting stale data and UI db retaining stale data - out of sync?

**To Reproduce**
Restart broker, monitor

Able to create instances
![image](https://user-images.githubusercontent.com/56970398/68087423-9e05c700-fe23-11e9-864a-1dd96be3ce44.png)

No Workflows in monitor (but likely server has it persisted, and active)

![image](https://user-images.githubusercontent.com/56970398/68087439-c2fa3a00-fe23-11e9-8f20-c4a24ec44d9c.png)

can see instances in Monitor
![image](https://user-images.githubusercontent.com/56970398/68087452-e45b2600-fe23-11e9-8477-74c076af4a70.png)

Clicking on WF id in UI  causes stacktrace
![image](https://user-images.githubusercontent.com/56970398/68087456-03f24e80-fe24-11e9-8142-239d0f353e7b.png)

**Environment:**
 - OS: Mac 
 - Zeebe Version: [e.g. 0.20.0]

**Comment by menski** [comment] 2019-11-04 10:54
I transferred this issue to the simple monitor repository as it does not seem to be related to the zeebe broker itself, as you are still able to create and complete instances.

**Comment by maghibus** [comment] 2020-03-24 18:45
Hi all,
I'm dealing with a similar issue

Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "job_pkey"
Detail: Key (key_)=(6755399441345456) already exists.

**Comment by ceefour** [comment] 2020-03-31 00:02
I also got this issue.

And my case is worse, I can't see any workflow even though Simple Monitor claimed it deployed the workflow successfully. Weird.

**Comment by saig0** [comment] 2020-04-21 04:50
@ceefour and  @maghibus: this sounds like a different issue. Please open a new issue and describe your setup and how to reproduce the behavior. 

> Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "job_pkey"

This is unexpected. The importer checks if the key exists before inserting a new entry.

**Comment by saig0** [comment] 2020-04-21 05:04
@anborg, by default the simple monitor just uses an **in-memory database**. So, the state is removed after a restart. If a new workflow instance is created in the broker then this instance is imported. This happens independently to the workflow. So, when you open the UI then the workflow can not be displayed.

To avoid this situation, you can configure a persistent database.

**Closed by saig0** 2020-04-21 05:04 UTC
